### ISSUE TITLE
NilClass# (OAuth2::Error) "<!DOCTYPE html>
<!-- Sorry dudes! 502 Error! -->
<html>
    <head>
        <title>AngelList in experience at a technical some difficulties</title>
    </head>
    <style>
      body {
        padding: 0;
        margin: 0;
     

### ISSUE THREAD

**Issue by stas** [Founden/doers#123]
<table><tr><th>Exception</th><td>&lt;!DOCTYPE html&gt;
&lt;!-- Sorry dudes! 502 Error! --&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;AngelList in experience at a technical some difficulties&lt;/title&gt;
    &lt;/head&gt;
    &lt;style&gt;
      body {
        padding: 0;
        margin: 0;
        background: #f2f3f5 url(https://s3.amazonaws.com/assets.angel.co/truck.png) repeat center top;
        width: 100%;
        display: table;
        height: 100%;
      }
      #outer {
        width: 100%;
        height: 100%;
        overflow: visible;
        position: relative;
      }
      #outer[id] {
        display: table;
        position: static;
      }
      #middle {
        position: absolute;
        top: 20%;
      }
      #middle[id] {
        display: table-cell;
        vertical-align: middle;
        width: 100%;
      }
      #inner {
        width: 50%;
        margin-left: auto;
        margin-right: auto;
        position: relative;
        top: -20%
      }
    &lt;/style&gt;
    &lt;body style=&quot;font-family: &#39;Helvetica Neue&#39;, Helvetica, Tahoma, Arial, Verdana, sans-serif;&quot;&gt;
      &lt;div id=&quot;outer&quot;&gt;
        &lt;div id=&quot;middle&quot;&gt;
          &lt;div id=&quot;inner&quot; style=&quot;margin: 0 auto; background-color: rgba(0,0,0,0.6); text-align: center; border-radius: 10px; box-shadow: 0px 3px 3px #000; padding: 40px 30px; font-weight: 200; font-size: 28px; color: #fff; text-shadow: 0 1px 0 #000;&quot;&gt;
                &lt;img style=&quot;height: 50px; border-radius: 3px; box-shadow: 0px 2px 2px #000;&quot; src=&quot;https://s3.amazonaws.com/assets.angel.co/peace.jpeg&quot; /&gt;
                &lt;p&gt;AngelList is experiencing technical difficulties. No server was available to process your request. We&#39;ve been notified, so please stay tuned.&lt;/p&gt;
          &lt;/div&gt;
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/body&gt;
&lt;/html&gt;</td></tr><tr><th>Last Occurrence</th><td>September 23, 2013 18:25:23 +0000</td></tr><tr><th>Count</th><td>3</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb#L110'>[app].../vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:110:in `request'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb#L134'>[app].../vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:134:in `get_token'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/strategy/auth_code.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/strategy/auth_code.rb:29:in `get_token'</a>
/home/deployer/app.doersapp.com/shared/bundle/ruby/2.0.0/bundler/gems/easy_auth-oauth2-da13184911dd/lib/easy_auth/models/identities/oauth2/base.rb:15:in `authenticate'
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth.rb:36:in `authenticate'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth/controllers/sessions.rb#L9'>[app].../vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth/controllers/sessions.rb:9:in `create'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb#L4'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L189'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:189:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb#L10'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:10:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:18:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L393'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:393:in `_run__2676669082529798166__process_action__callbacks'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L31'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb#L20'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb#L245'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L136'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb#L44'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L195'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb#L13'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L231'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L48'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L71'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L655'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.1/lib/party_foul/middleware.rb#L8'>[app].../vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.1/lib/party_foul/middleware.rb:8:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb#L23'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb#L11'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb#L241'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L225'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L220'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb#L486'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb#L626'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L373'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__2474783529354058573__call__callbacks'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb#L76'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L38'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb#L83'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb#L511'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb#L97'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/server.rb#L486'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/server.rb:486:in `handle_request'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/server.rb#L357'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/server.rb:357:in `process_client'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/server.rb#L250'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/server.rb:250:in `block in run'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/thread_pool.rb:92:in `call'</a>
<a href='https://github.com/stas/doers/blob/e330ac6ad3b6af634d3e453c08e5503f6ee179e5/vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.6.0/lib/puma/thread_pool.rb:92:in `block in spawn_thread'</a></pre>

Fingerprint: `f1a98e830f84b466151cb799e13c85b04f36ad81`

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>September 23, 2013 18:24:43 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=9b3200fd42cb0ba6cba57e7d3ffae53e</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>September 23, 2013 18:25:00 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=0e9ef9a3c2a67adcf791b4d3a3a134bf</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>September 23, 2013 18:25:23 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=2d2daae302b24c9f7c3f0aa9ddba2e0e</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
