### ISSUE TITLE
NilClass# (NoMethodError) "undefined method `angel_list_id' for #<User:0xXXXXXX>"

### ISSUE THREAD

**Issue by stas** [Founden/doers#44]
<table><tr><th>Exception</th><td>undefined method `angel_list_id&#39; for #&lt;User:0x007f5277a19b38&gt;</td></tr><tr><th>Last Occurrence</th><td>July 25, 2013 22:51:08 +0000</td></tr><tr><th>Count</th><td>2</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb#L436'>[app].../vendor/bundle/ruby/2.0.0/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in `method_missing'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb#L131'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:131:in `method_missing'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L134'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:134:in `custom_data_value_from_proc_or_symbol'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L128'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:128:in `block in custom_data_from_config'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L127'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:127:in `each'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L127'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:127:in `reduce'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L127'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:127:in `custom_data_from_config'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L44'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:44:in `custom_data'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/proxy.rb:25:in `to_hash'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/script_tag.rb#L65'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/script_tag.rb:65:in `find_current_user_details'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/script_tag.rb#L20'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/script_tag.rb:20:in `initialize'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb#L57'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb:57:in `new'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb#L57'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb:57:in `intercom_script_tag'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb:36:in `include_javascript?'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb#L16'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb:16:in `filter'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb#L6'>[app].../vendor/bundle/ruby/2.0.0/gems/intercom-rails-0.2.23/lib/intercom-rails/auto_include_filter.rb:6:in `intercom_rails_auto_include'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L407'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:407:in `_run__1994774741881464763__process_action__callbacks'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L31'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb#L20'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb#L245'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L136'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb#L44'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L195'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb#L13'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L231'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L48'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L71'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L655'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.0/lib/party_foul/middleware.rb#L8'>[app].../vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.0/lib/party_foul/middleware.rb:8:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb#L23'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb#L11'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb#L241'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L225'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L220'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb#L486'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb#L626'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L373'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__3733217743080988534__call__callbacks'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb#L76'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L38'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb#L83'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb#L511'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb#L97'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb#L381'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb:381:in `handle_request'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb#L252'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb:252:in `process_client'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb#L151'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb:151:in `block in run'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb:92:in `call'</a>
<a href='https://github.com/stas/doers/blob/47d2bfd36c663f9f81dde9612b60f82539dac772/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb:92:in `block in spawn_thread'</a></pre>

Fingerprint: `d0efe919e85523f2d08d09b57725658cc4675d18`

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>July 25, 2013 22:42:41 +0000</td></tr><tr><th>URL</th><td>[GET] /waiting</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>waiting</td></tr><tr><th>controller</th><td>pages</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/28.0.1500.52 Chrome/28.0.1500.52 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>July 25, 2013 22:51:08 +0000</td></tr><tr><th>URL</th><td>[GET] /waiting</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>waiting</td></tr><tr><th>controller</th><td>pages</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/28.0.1500.52 Chrome/28.0.1500.52 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
My fault. Closed.
