### ISSUE TITLE
NilClass# (Faraday::Error::ResourceNotFound) "the server responded with status 404"

### ISSUE THREAD

**Issue by stas** [Founden/doers#69]
<table><tr><th>Exception</th><td>the server responded with status 404</td></tr><tr><th>Last Occurrence</th><td>November 22, 2013 16:50:22 +0000</td></tr><tr><th>Count</th><td>4</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response/raise_error.rb#L6'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response/raise_error.rb:6:in `on_complete'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response.rb#L9'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response.rb:9:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response.rb#L63'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response.rb:63:in `on_complete'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response.rb#L8'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/response.rb:8:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/request/url_encoded.rb#L14'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/request/url_encoded.rb:14:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/connection.rb#L253'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/connection.rb:253:in `run_request'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/connection.rb#L106'>[app].../vendor/bundle/ruby/2.0.0/gems/faraday-0.8.8/lib/faraday/connection.rb:106:in `get'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/bundler/gems/oembedr-1a51c9f060f9/lib/oembedr/client.rb#L41'>[app].../vendor/bundle/ruby/2.0.0/bundler/gems/oembedr-1a51c9f060f9/lib/oembedr/client.rb:41:in `get'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/bundler/gems/oembedr-1a51c9f060f9/lib/oembedr.rb#L22'>[app].../vendor/bundle/ruby/2.0.0/bundler/gems/oembedr-1a51c9f060f9/lib/oembedr.rb:22:in `fetch'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/app/controllers/api/v1/embeds_controller.rb#L9'>[app].../app/controllers/api/v1/embeds_controller.rb:9:in `index'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb#L4'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L189'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:189:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb#L10'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:10:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:18:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L393'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:393:in `_run__1108753925764297043__process_action__callbacks'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L31'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb#L20'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb#L245'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L136'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb#L44'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L195'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb#L13'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L231'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L48'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L71'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L655'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.0/lib/party_foul/middleware.rb#L8'>[app].../vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.0/lib/party_foul/middleware.rb:8:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb#L23'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb#L11'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb#L241'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L225'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L220'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb#L486'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb#L626'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L373'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__2369883043303502908__call__callbacks'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb#L76'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L38'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb#L83'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb#L511'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb#L97'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb#L381'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb:381:in `handle_request'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb#L252'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb:252:in `process_client'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb#L151'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/server.rb:151:in `block in run'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb:92:in `call'</a>
<a href='https://github.com/stas/doers/blob/11d090bb64bf99d8c331e7c016cd7b4eaefde9e7/vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.0/lib/puma/thread_pool.rb:92:in `block in spawn_thread'</a></pre>

Fingerprint: `34ba81a33970b4ff10ff6e664c1a7274273273e6`

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>August 05, 2013 13:17:38 +0000</td></tr><tr><th>URL</th><td>[GET] /api/v1/embeds?url=https%3A%2F%2Ftwitter.com%2Fbfeld</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/embeds</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>application/json, text/javascript, */*; q=0.01</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>November 22, 2013 16:47:20 +0000</td></tr><tr><th>URL</th><td>[GET] /api/v1/embeds?url=https%3A%2F%2Ftwitter.com%2Fcdibona</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/embeds</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>78.97.214.143</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:25.0) Gecko/20100101 Firefox/25.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/javascript, */*; q=0.01</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>November 22, 2013 16:50:21 +0000</td></tr><tr><th>URL</th><td>[GET] /api/v1/embeds?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGBwlgSIaeDs%2F</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/embeds</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>78.97.214.143</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:25.0) Gecko/20100101 Firefox/25.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/javascript, */*; q=0.01</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>November 22, 2013 16:50:22 +0000</td></tr><tr><th>URL</th><td>[GET] /api/v1/embeds?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGBwlgSIaeDs%20[HTTP/1.1%20200%20OK%20235ms]</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>api/v1/embeds</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>78.97.214.143</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:25.0) Gecko/20100101 Firefox/25.0</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>
