### ISSUE TITLE
NilClass# (OAuth2::Error) "invalid_grant: The given code has expired.
{"error":"invalid_grant","error_description":"The given code has expired."}"

### ISSUE THREAD

**Issue by stas** [Founden/doers#78]
<table><tr><th>Exception</th><td>invalid_grant: The given code has expired.
{&quot;error&quot;:&quot;invalid_grant&quot;,&quot;error_description&quot;:&quot;The given code has expired.&quot;}</td></tr><tr><th>Last Occurrence</th><td>November 14, 2013 23:28:32 +0000</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace

<pre><a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb#L110'>[app].../vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:110:in `request'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb#L134'>[app].../vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:134:in `get_token'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/strategy/auth_code.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/oauth2-0.9.2/lib/oauth2/strategy/auth_code.rb:29:in `get_token'</a>
/home/deployer/app.doersapp.com/shared/bundle/ruby/2.0.0/bundler/gems/easy_auth-oauth2-da13184911dd/lib/easy_auth/models/identities/oauth2/base.rb:15:in `authenticate'
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth.rb:36:in `authenticate'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth/controllers/sessions.rb#L9'>[app].../vendor/bundle/ruby/2.0.0/bundler/gems/easy_auth-4cf8104ebad3/lib/easy_auth/controllers/sessions.rb:9:in `create'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb#L4'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L189'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:189:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb#L10'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:10:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:18:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L393'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:393:in `_run__4000768410443384515__process_action__callbacks'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L31'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb#L20'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb#L159'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb#L245'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb#L18'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb#L136'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb#L44'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L195'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb#L13'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb#L231'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L48'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L71'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb#L59'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb#L655'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.0/lib/party_foul/middleware.rb#L8'>[app].../vendor/bundle/ruby/2.0.0/gems/party_foul-1.3.0/lib/party_foul/middleware.rb:8:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb#L23'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb#L11'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb#L241'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L225'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb#L220'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb#L486'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb#L36'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb#L626'>[app].../vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L29'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L373'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__787815521717304025__call__callbacks'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb#L80'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb#L27'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb#L76'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L38'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L25'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb#L67'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb#L21'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb#L17'>[app].../vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb#L83'>[app].../vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb#L511'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb#L97'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb#L30'>[app].../vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/server.rb#L472'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/server.rb:472:in `handle_request'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/server.rb#L343'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/server.rb:343:in `process_client'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/server.rb#L242'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/server.rb:242:in `block in run'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/thread_pool.rb:92:in `call'</a>
<a href='https://github.com/stas/doers/blob/f4a7f1c983f67792c4c15e55a302253362ff7856/vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/thread_pool.rb#L92'>[app].../vendor/bundle/ruby/2.0.0/gems/puma-2.4.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'</a></pre>

Fingerprint: `f96b0bb0223be0963253ad35ce030c9d9045c8ae`

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>August 09, 2013 18:31:17 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=c37ca4ac061e5259c7579851f733142e</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100721 Firefox/3.6.8</td></tr><tr><th>Accept Encoding</th><td>identity</td></tr><tr><th>Accept</th><td>text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5</td></tr></table></td></tr></table>

**Comment by stas** [comment]
Jesus... broken browsers.

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>September 23, 2013 13:59:42 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=ac1d580ac4294937c7df4a116cb9c5de</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>127.0.0.1</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.76 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>November 01, 2013 22:06:49 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=0ada977c128bc10cd7c4549c4e526d12</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>159.63.21.186</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>November 04, 2013 21:42:58 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=89700701caa15a120f60f2986560b6dc</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>159.63.21.186</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by stas** [comment]
<table><tr><th>Occurred At</th><td>November 14, 2013 23:28:32 +0000</td></tr><tr><th>URL</th><td>[GET] /sign_in/oauth2/angel_list/callback?code=3788360e3cbe906d38ed975c3102c700</td></tr><tr><th>Params</th><td><table><tr><th>identity</th><td>oauth2</td></tr><tr><th>controller</th><td>sessions</td></tr><tr><th>action</th><td>create</td></tr><tr><th>provider</th><td>angel_list</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>159.63.21.186</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.0</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.48 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip,deflate,sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>
